---
- hosts: workshop_machines
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  tasks:

    - name: gethosts
      debug:
        var: inventory_hostname

    - name: fetch and store secrets
      block:
      - name: get_secrets_from_vault
        set_fact:
            proxmox_user_secret: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/' + inventory_hostname + '/' , engine_mount_point='keyvalue', url='http://127.0.0.1:8200',  token=vault_token) }}"

      - name: save secrets in inventory
        set_fact:
          ansible_ssh_host: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['ip'] }}"
          ansible_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['user'] }}"
          ansible_ssh_pass: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['pass'] }}"
          ansible_become_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['pass'] }}"
      - name: save additional secrets for dcworkshop2
        set_fact:
          ilo_ip: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['ilo_ip'] }}"
          ilo_pass: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['ilo_pass'] }}"
          ilo_user: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/proxmox/'+ inventory_hostname, engine_mount_point='keyvalue', url='http://127.0.0.1:8200', token=vault_token)['data']['data']['ilo_user'] }}"
        when: inventory_hostname == 'dcworkshop2'

- hosts: dcworkshop2
  gather_facts: no

  collections:
  - ji_podhead.ilohelper
  tasks:

    - name: wait_for_boot
     # no_log: true
      ilohelper:
        iLO: "{{ ilo_ip }}"
        login_account: "{{ ilo_user }}"
        login_password: "{{ilo_pass}}"
        target_ip: "{{ansible_ssh_host}}"
        command: "get_server_status"
      delegate_to: "localhost"
      register: script_output

    - name: Display script output
      ansible.builtin.debug:
        var: script_output.stdout_lines
