name: Redirect PR to Private Repo

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      uses: actions/setup-git@v2
      with:
        git-config: |
          config.user.email "action@github.com"
          config.user.name "GitHub Action"
          
    - name: Redirect PR
      run: |
        git remote remove origin
        git remote add origin ${{ secrets.PRIVATE_REPO_URL }}
        git branch -M master
        git checkout -b ${{ github.head_ref }}
        git push -u origin ${{ github.head_ref }}
        
    - name: Delete original PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Redirected PR to private repo"
        title: "Closed original PR"
        body: "This PR has been redirected to the private repository."
        labels: "closed"
