name: Redirect PR or Push to Private Repo
on:
  pull_request:
    types: [opened, synchronize]
  push:
   # branches-ignore: [main] #
    branches:
    - development
jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ji-podhead/Pod-Shop-App-Configs-private
          ref: 'test'
          token:  ${{ secrets.PODSHOP_PRIVATE_PAT }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      #- <make changes and commit >
      #- run: git push origin master
      
  
  
