name: merge_from_private

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**'
      - 'merge_private'

jobs:
  merge_from_private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: merge_private
      - name: git config
        run: |
          BRANCH_NAME="temp-pr-${{ github.run_id }}"
          git config --global user.email "bot@ji-podhead.com"
          git config --global user.name "pod shop bot"  
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository:  ji-podhead/App-Configs-private 
          token: ${{ secrets.PRIVATE_PAT }}
          path: development
          fetch-depth: 0 # Optional: Fetches all history for all tags and branches
    
          # Weitere Schritte...



      - name: Push to target repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: the-pod-shop/Pod-Shop-App-Configs 
          branch: merge_private
          directory: ./
    
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: 'the-pod-shop/App-Configs-private'
          path: 'merge_private'
          fetch-depth: 0 # Optional: Fetches all history for all tags and branches
    
     
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB  }}
          commit-message: "Merge private branch with code from another repo"
          title: "Merge private branch with external code"
          body: "This PR merges the newly created 'merge_private' branch which contains code from another repo."
          branch: merge_private
          base: development
